default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'user_name' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'user_password' } %>
  host: db

development:
  <<: *default
  database: webapp_development

test:
  <<: *default
  database: webapp_test

# production:
#   <<: *default
#   database: webapp_production
#   username: webapp
#   password: <%= ENV['WEBAPP_DATABASE_PASSWORD'] %>
